main: fr.ferdinandklr.nullstorage.main
name: nullstorage
version: 0.1.2
api-version: 1.16

author: Ferdinand Keller

permissions:
  nullstorage.command.nullstorage:
    description: allows players to create null storage crates with a command
    default: false

commands:
  nullstorage:
    description: gives to the player a null storage box
    usage: /<command>
    permission: nullstorage.command.nullstorage
    default: op